### ISSUE TITLE
set properties adds a ";" for the first key in case of multiple key/value pair

### ISSUE THREAD

**Issue by ashok2285** [jfrog/jfrog-cli-go#135]
Hi,

I am using jfrog version 1.13.1 and encountering issue with set-props.
Command seems to add an ';' which I don't intend. Attached is the image.
Command used: jfrog rt sp --url "https//...." "my_repo/my_file.bin" "key2=value2|key3=value3"

replacing pipe by ';' doesn't set the properties.

![image](https://user-images.githubusercontent.com/36765173/36595483-a557da42-18a2-11e8-9f3f-8d5f4ff43085.png)

As a work around a pipe at the beginning pushes the extra semicolon as a new property

command: jfrog rt sp --url "https//...." "my_repo/my_file.bin" "|key2=value2|key3=value3"
![image](https://user-images.githubusercontent.com/36765173/36595995-83538ff2-18a4-11e8-873d-7e1606a08bea.png)

**Comment by eyalbe4** [comment]
@ashok2285,
Do you experience the same issue with the latest release (1.14.0)?

**Comment by ashok2285** [comment]
yes,
jfrog.exe --version
jfrog version 1.14.0

**Comment by DimaNevelev** [comment]
@ashok2285 ,
Thank you for reporting this, we [committed a fix](https://github.com/JFrogDev/jfrog-cli-go/commit/a89f35ce808ff80af3048867562f1d3430274c28) for the problem which will be included in our upcoming release.

**Comment by eyalbe4** [comment]
@ashok2285,
Did you get a chance to test this with the latest JFrog CLI release?
