### ISSUE TITLE
jfrog rt cp copies artifact in nested location

### ISSUE THREAD

**Issue by rajatjindal** [jfrog/jfrog-cli-go#136]
jfrog rt cp --server-id lab local-repo/projectname/1.1-15 prod-repo/projectname/1.1-15 

[Info] Searching artifacts...
[Info] Found 1 artifact.
[Info] Copying artifact: local-repo/projectname/1.1-15/ to: prod-repo/projectname/projectname/1.1-15

{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}

refer to log copying artifact, it copies it at projectname/projectname/version instead of projectname/version

**Comment by eyalbe4** [comment]
@rajatjindal,
Notice that for the *jfrog rt cp* command, the default value for the *flat* option is *false*. Try setting it to *true". Let us know if you need further help with this.

**Comment by rajatjindal** [comment]
$ jfrog rt cp --server-id lab local-repo/projectname/1.1-15 prod-repo/projectname/1.1-15 --flat true

[Error] Wrong number of arguments. You can read the documentation at https://www.jfrog.com/confluence/display/CLI/JFrog+CLI

I also tried with just --flat, same error still.

**Comment by eyalbe4** [comment]
@rajatjindal,
You're now getting:
**Wrong number of arguments.**
This is different than the output you posted initially.
You should construct the command correctly, and avoid mixing the arguments and the command options.

**Comment by rajatjindal** [comment]
What do you mean mix arguments and command options, 

Anyways i tried —flat just after —server-id too and before it as well, none worked

Can you please give a sample cp command with —flat used in it

Thanks

**Comment by DimaNevelev** [comment]
@rajatjindal ,
In the documentation you can find the definitions of all the arguments and the options. 
Your command structured as: `"jfrog rt cp option argument argument option"`. The cli will accept only commands in one of the following forms:
```
"jfrog rt cp options... arguments..."
or
"jfrog rt cp arguments... options..."

```
In your case:
```
 jfrog rt cp --server-id lab --flat true local-repo/projectname/1.1-15 prod-repo/projectname/1.1-15 
or
 jfrog rt cp local-repo/projectname/1.1-15 prod-repo/projectname/1.1-15 --server-id lab --flat true
```

**Comment by eyalbe4** [comment]
@rajatjindal ,
I'm closing this issue. Do let us know if you need additional assistance.
