### ISSUE TITLE
msbuild and nuget support

### ISSUE THREAD

**Issue by NasAmin** [jfrog/jfrog-cli-go#138]
Are there any plans to support build-info generation for msbuild and nuget packages?

regards,

Nas

**Comment by eyalbe4** [comment]
Absolutely @NasAmin.
We're currently working on researching and designing a build integration solution which should integrate JFrog CLI with nuget and msbuild.

**Comment by eyalbe4** [comment]
@NasAmin,
The latest release of JFrog CLI includes a new **jfrog rt nuget** command, allowing resolution of nugert packages while recording build-info. You can read more about it in the [Building Nuget Packages](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildingNugetPackages) documentation section.
In addition, we updated the [msbuild-example](https://github.com/jfrog/project-examples/tree/master/msbuild-example) for a quick start up.
We'd appreciate your feedback for the new functionality.
