### ISSUE TITLE
Error should be throw when a 403 is returned from the server

### ISSUE THREAD

**Issue by shawnbutts** [jfrog/jfrog-cli-go#145]
What i'm seeing (via strace) with `jfrog rt dl --url http://privateserver:8081/artifactory --threads 5 /a.spec` is that a 403 is being returned the server and jfrog-cli-go just hangs with `[Info] Searching items to download...`

**Comment by elhigu** [comment]
I was experiencing the same kind of hanging and `jfrog rt search` command actually in my case gave more information why (some authentication problem). Anyways my workaround was to use jfrog client version 1.13.1.

**Comment by yahavi** [comment]
@shawnbutts & @elhigu 
Thanks for reporting this issue.
We fix this issue in the latest release v1.16.0. Feel free to upgrade.
We'll appreciate you feedback for that.
