### ISSUE TITLE
JFROG_CLI_HOME misinterpreted

### ISSUE THREAD

**Issue by kPshi** [jfrog/jfrog-cli-go#172]
While working with different config files via JFROG_CLI_HOME I found that another /.jfrog is appended to the configured directory.
```
jfrog --help
[...]
	JFROG_CLI_HOME
		[Default: ~/.jfrog]
		Defines the JFrog CLI home directory path.
```
so actually setting it to the default value should not change anything, but
```
export JFROG_CLI_HOME=~/.jfrog

strace 2>&1 jfrog rt u --recursive swshare{,} | grep /\\.jfrog
stat64("/home/x/.jfrog/.jfrog", 0x18e22384) = -1 ENOENT (No such file or directory)
stat64("/home/x/.jfrog", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
mkdirat(AT_FDCWD, "/home/x/.jfrog/.jfrog", 0777) = 0
stat64("/home/x/.jfrog/.jfrog/jfrog-cli.conf", 0x18e224a4) = -1
```
So that either the documentation (--help) is incorrect or the variable is not interpreted correctly. Personally I think it's the latter.

Using jfrog CLI 1.16.0 on Ubuntu 16.04.4 LTS

**Comment by eyalbe4** [comment]
Than you for letting us know @kPshi.
We consider this a bug and we intend to fix it. We'll fix it in a way that will not affect anyone who's already using this environment variable. 
We'll update this issue after fixing the issue.

**Comment by RobiNino** [comment]
Hi @kPshi,
A new environment variable, JFROG_CLI_HOME_DIR, was introduced in Jfrog CLI version 1.21.0.
This variable is interpreted correctly and replaces the old JFROG_CLI_HOME variable.

Thanks for pointing this issue out, we'll appreciate your feedback regarding this matter.
