### ISSUE TITLE
Add Dockerfile and push to Docker hub

### ISSUE THREAD

**Issue by arbourd** [jfrog/jfrog-cli-go#179]
Hello 👋 

We use this CLI in CI and it would nice to have an official Docker image and build to use. Modern CIs like Concourse and Circle can easily use Docker images instead of having to curl bins.

**Comment by eyalbe4** [comment]
Agree @arbourd!
If you'd like to contribute a Dockerfile, we can use it to create the image.

**Comment by arbourd** [comment]
On it! 🤓
