### ISSUE TITLE
jfrog can not publish go deps to artifactory

### ISSUE THREAD

**Issue by yg-xue** [jfrog/jfrog-cli-go#186]
Latest vgo uses a different folder path for dependencies:

Old version vgo downloads dependencies to goPath\src\v\cache.
The latest vgo downloads dependencies to goPath\src\mod\cache\download.
Currently, jfrog-cli-go load go dependencies from filepath.Join(goPath, "src", "v", "cache").

Needs to update in order to support the new vgo.

**Comment by eyalbe4** [comment]
Thanks @yg-xue.
We're already working on the compatibility fixes.
We'll update here soon.

**Comment by yg-xue** [comment]
@eyalbe4 
Thanks for the update.
