### ISSUE TITLE
jfrog rt cp/mv commands fail with x509: certificate signed by unknown authority when using self-signed CA certificate

### ISSUE THREAD

**Issue by lexa2** [jfrog/jfrog-cli-go#187]
Looks like a regression been introduced somewhere between jcli 1.11.2 and 1.10.2.
Using exactly the same configuration I'm able to upload and download files to/from our Artifactory server. But when I try to do "jfrog rt cp" or "jfrog rt mv" I'm presented with x509 error with jfrog CLI 1.11.2. Rolling back to 1.10.2 makes the issue go away.

Unfortunately rolling back to 1.11.2 is not a solution for me as some boxes I use require http/https proxy to access the Artifactory. I had tried cp/mv with latest available jfrog 1.17.0 and it also fails.

Please check what's wrong and fix this regression. Thanks in advance.

**Comment by eyalbe4** [comment]
@lexa2,
The JFrog CLI source code comes with a test whuch generates self signed certificates, sets up a reverse proxy and validates that this functionality works.
See the *TestArtifactorySelfSignedCert* functionality in [artifactory_test.go](https://github.com/jfrog/jfrog-cli-go/blob/master/jfrog-cli/jfrog/artifactory_test.go). These tests pass for us. If you're able to run the tests (you should run the *Artifactory Generic Tests* -  see the instructions in this repository's RRADME on how to do this) thrn perhaps it could provide a hint to the cause of the issue you're experiencing.

**Comment by lexa2** [comment]
From what I see tests do not cover the case when CA is self-signed and then there's server's cert that is signed by that CA. Unfortunately I do not have Go build environment set up locally and it is forbidden by corporate rules to set it up myself on my working box :-(. Are there any other ways to get more debug output from jcli? JFROG_CLI_LOG_LEVEL="DEBUG" is not verbose enough to get an insight on what's going wrong. 

Nevertheless, situation is like this: I've got jfrog-1.10.2, jfrog-1.11.2 and jfrog-1.17.0 binaries sitting next to each other in a single folder. I execute "jfrog rt cp repo1/dir1/artifacts*.rpm repo1/dir2/" command using version 1.10.2 - works fine. Then I delete copied artifacts through web interface and repeat using 1.11.2 without any other config changes. It fails with "Post <atifactory URL>/api/copy/repo1/dir1/artifacts-1.2.3.rpm?to=repo1%2Fdir2@2Fartifacts-1.2.3.rpm: x509: certificate signed by unknown athority". Lastly I try 1.17.0 and got exactly the same error message. This behavior makes me believe that some regression was introduced between 1.10.2 and 1.11.2, possibly it might be related to proxy support.

**Comment by eyalbe4** [comment]
@lexa2,
My apologies for the late response here.
We identified the bug and pushed [this](https://github.com/jfrog/jfrog-cli-go/commit/36ac096020f5ef6a1ffe92ed6f763fc33ec5dec9) commit to the *dev* branch with the fix.
We'll soon release a patch with this fix.

**Comment by lexa2** [comment]
@eyalbe4 Thanks for keeping me informed. I had also submitted this bug through the vendors relations department of the company I work for so don't be surprised if another identically-looking report would hit you from the enterprise support side. Please inform me when a new jcli binary would be available to test if this bug was fixed. Thanks again for working on this.

**Comment by eyalbe4** [comment]
@lexa2,
Version 1.20.1 has been released and includes this fix.
Looking forward to your feedback for it.
Thanks

**Comment by lexa2** [comment]
@eyalbe4 Confirming fixed in 1.20.1. Thank you.
