### ISSUE TITLE
Unwanted empty directory created on rt download

### ISSUE THREAD

**Issue by gsemet** [jfrog/jfrog-cli-go#189]
Let say I have the following configuration:
```
reponame/path/to/a/folder/subdir/artifact1
reponame/path/to/a/folder/subdir/artifact2
reponame/path/to/a/folder/subdir/artifact3
```

I wish to download the content of reponame/path/to/a/folder/ so that I get a local directory `subdir/*`, so I use:
```bash
jfrog cli rt download --recursive --flat=True --include-dirs=true --server-id arti "reponame/path/to/a/folder/(*)" "{1}"
```
The wanted files as well downloaded but an extra empty directory `subdir/subdir/` is being created:
```
subdir/
subdir/artifact1
subdir/artifact2
subdir/artifact3
subdir/subdir/
```
This might pollute automated systems. For example I use it to download my pypi package from a previous build and when I push `dist/(*)` it complains about `dist/dist` not being a valid Python package.

Is it possible to avoid creating this extra folder for nothing? Thanks

JFrog CLI: 1.16.1

**Comment by eyalbe4** [comment]
@gsemet,
You  try to include *subdir* as part of your source pattern, and also add it to the target path:

```
jfrog rt download --recursive --flat=true --include-dirs=true --server-id arti "reponame/path/to/a/folder/subdir/(*)"  "subdir/{1}"
```
Also, the *include-dirs* option makes the command match directorie (subdir) and not only files, with the source pattern.

Let me know if this helps.

**Comment by gsemet** [comment]
I may not know the subdir part of the part. And it may have other subdirectories. 

If I remove —include-dirs, will I get my expected behavior? I want everything under reponame/path/to/a/folder and have exactly the same content, relative to this path, reproduced on my local drive.

**Comment by eyalbe4** [comment]
Yes @gsemet,
I believe removing thid option should not include that folder in the download pattern.

**Comment by gsemet** [comment]
By not including the subdirectories argument the behavior seems the right one. I do not see the use case for which this argument should be used?

**Comment by eyalbe4** [comment]
In some cases, you want the pattern to include directories as well. For example, if you'd like empty directories to be recreated on the local file system as well. There are probably other use cases where this option can come in handy.

**Comment by gsemet** [comment]
Thanks for your help !
