### ISSUE TITLE
vgo proxy compatibility broken in latest go beta release and current vgo head

### ISSUE THREAD

**Issue by trashhalo** [jfrog/jfrog-cli-go#194]
From what I can tell its this encoding behavior
https://github.com/golang/vgo/blame/20939850793927db78c179dcfcd5d4d6f44f2c01/vendor/cmd/go/internal/module/module.go#L368-L461

original issue I made on golang. whole bunch of context over there https://github.com/golang/go/issues/26503

**Comment by eyalbe4** [comment]
@trashhalo,
Thank you for reporting this. We're currently looking into this issue. Wie'll update soon.

**Comment by eyalbe4** [comment]
@trashhalo,
We have [RTFACT-17178](https://www.jfrog.com/jira/browse/RTFACT-17178) to track this issue, so I think that we can close this one for now.
