### ISSUE TITLE
CLI upload to Artifactory fails when Paths are enclosed in single quotes

### ISSUE THREAD

**Issue by akhanna38** [jfrog/jfrog-cli-go#196]
CLI upload to Artifactory fails when Paths are enclosed in single quotes

OS: Windows
CLI version: 1.17.1

This does not work: 
jfrog rt upload 'sourcepath' 'destination'

These work
jfrog rt upload "sourcepath" "destination"
jfrog rt upload sourcepath destination

**Comment by eyalbe4** [comment]
@akhanna38,
Did this ever work? Why aren't you using double quotes?

**Comment by akhanna38** [comment]
No idea if it ever worked or not. I am following the TFS Deployer addin logs and using single quotes. If i use double quotes i get issues with regular expressions

**Comment by DimaNevelev** [comment]
@akhanna38 ,
Single quotes should not be used in windows command line, please use double quotes instead. It is a windows cmd behaviour, you can get more information [here](https://superuser.com/questions/324278/how-to-make-windows-command-prompt-treat-single-quote-as-though-it-is-a-double-q).
As for the issue with regular expression - please provide us more information, such as log at debug log level, the exact command you are running and any information you think can help us.
The CLI log level can be changed to debug by setting the environment variable "JFROG_CLI_LOG_LEVEL=DEBUG".

**Comment by eyalbe4** [comment]
@akhanna38,
Adding to @DimaNevelev's reply, there's a new Artifactory VSTS Extension which is about to be released soon.
It will include significant improvements, specifically in the way it triggers JFrog CLI.
We'll let you know when it is out.

**Comment by eyalbe4** [comment]
@akhanna38,
Did you get a chance to try out the new [Artifactory VSTS Extension](https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-artifactory-vsts-extension)? Did it resolve the issue?

**Comment by eyalbe4** [comment]
@akhanna38,
I'm closing this issue for now.
Do let us know if you need further assistance.
