### ISSUE TITLE
TFS JFrog Artifactory Deployer Plugin is not working 

### ISSUE THREAD

**Issue by akhanna38** [jfrog/jfrog-cli-go#197]
TFS JFrog Artifactory Deployer Plugin is not working and stuck after pinging the server.

it is using single quotes in the command instead of double quotes and affected by issue #196

**Comment by eyalbe4** [comment]
@akhanna38,
This VSTS extension has been recently deprecated and replaced with the new [JFrog Artifactory](https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-artifactory-vsts-extension) VSTS Extension. The new extension fixes this issue and is much more robust.
Please let us know if you need further assistance with it.

**Comment by eyalbe4** [comment]
@akhanna38,
With your permission, I'm closing this issue for now. Please let us know if you need additional help.
