### ISSUE TITLE
Dangling symlink in Go module causes `no such file or directory`

### ISSUE THREAD

**Issue by al4** [jfrog/jfrog-cli-go#199]
I realise this is all very new, but versioning and artifactory support for Go is something I've been wanting for a while!

The trouble is, I was unable to publish my first module:
```
jfrog rt go-publish go 0.0.1 --url=https://[user]:[pass]@[company].jfrog.io/[artifactory]
[Info] Using vgo: go version go1.10.3 darwin/amd64 vgo:devel +88c76dcbab

[Info] Publishing project...
[Info] Publishing github.com/starlingbank/vaultsmith:0.0.1 to go
[Error] open [$GOPATH]/src/github.com/starlingbank/vaultsmith/vendor/github.com/hashicorp/go-rootcerts/test-fixtures/capath-with-symlinks/securetrust.pem: no such file or directory
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
[Error] Publishing project finished with errors. Please review the logs.
```

The problem is that the hashicorp go-rootcerts module ends up including a symlink to a file that does not exist; the file `capath-with-symlinks/securetrust.pem` is a symlink to `../capath/securetrust.pem` which for some reason isn't included in the build ([it is present in the repository though](https://github.com/hashicorp/go-rootcerts/tree/master/test-fixtures)).

Digging into the code, I found where the file is added to the archive, and was able to make it "work" with the code in [this commit](https://github.com/al4/jfrog-cli-go/commit/fcd3125aec087eb88c6f9ce4a11ba6ad0485872d). jfrog-cli built with my branch gives: 
```
[Info] Using vgo: go version go1.10.3 darwin/amd64 vgo:devel +88c76dcbab

[Info] Publishing project...
[Info] Publishing github.com/starlingbank/vaultsmith:0.0.1 to go
[Info] Publishing project dependencies...
{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}
```

I'm in no way suggesting it should be merged though as it's actually broken. While it writes the contents of the link to the zip file, on extraction, it is no longer a symlink, but a plain file with the target path as contents. As far as I can tell, archive/zip does not support symlinks. 

I'm not really sure where the responsibility for this problem lies. Even if the target file was included in the archive, jfrog cli would store the link as a file, which would clearly break the logic of hashicorp's test.

On the other hand it's a little mystifying to me that `capath-with-symlinks` is included in my vendor dir, but `capath` is not. I think this is a separate issue though.

Could jfrog-cli be made to store symlinks as-is? Should it?

**Comment by al4** [comment]
I should also note; removing the offending symlinks fixed my issue. The _test.go files that reference the fixtures in hashicorp's module were not being included, so it looks like a bug in vgo that the symlinks were present at all.

Thus I'm not sure there's a use case where a symlink is required, and replacing it with the target file isn't sufficient.

**Comment by eyalbe4** [comment]
Thanks you for sharing this @al4!
This information may be useful to others who may encounter this issue.
Do you know if the issue is fixed in the latest version of vgo or go? (JFrog CLI 1.18 and above no longer triggers vgo, but expects go 1.11 (or one of its release candidates).

**Comment by al4** [comment]
Thanks for the reply @eyalbe4, it works now (using go 1.11 and jfrog-cli 1.19):
```$ export GO111MODULE=on
$ jfrog rt go-publish go 0.0.4-1 --apikey=[key] --url=https://[artifactory]
[Info] Using go: go version go1.11 darwin/amd64

[Info] Publishing project...
[Info] Publishing github.com/starlingbank/vaultsmith:0.0.4-1 to go
[Info] Publishing project dependencies...
{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}```
