### ISSUE TITLE
rt uploads intermittently eventually fail with EOF, after many files succeed

### ISSUE THREAD

**Issue by BrBill** [jfrog/jfrog-cli-go#201]
Uploads fail (as shown in the attached logged output of a jfrog rt upload with DEBUG reporting), with messages like this:

[Debug] Uploaded 957 artifacts.
[Error] Failed uploading 1 artifacts.
[Error] unexpected EOF
{
  "status": "failure",
  "totals": {
    "success": 957,
    "failure": 1
  }
}
[Error] Upload finished with errors. Please review the logs

Catalina and Artifactory logs show no info about failures or communications problems, so reviewing the logs is fruitless.

Tried breaking up into smaller groups, but the problem still happens.

[jfrog_DEBUG_output.txt](https://github.com/jfrog/jfrog-cli-go/files/2295153/jfrog_DEBUG_output.txt)

**Comment by DimaNevelev** [comment]
@BrBill,
We are looking into this issue.

**Comment by eyalbe4** [comment]
@BrBill,
https://github.com/jfrog/jfrog-cli-go/pull/215 created by @DimaNevelev adds upload retries and may resolve the issue you'r experiencing. It is currently merged into the *dev* branch and will be part of the upcoming release.

**Comment by eyalbe4** [comment]
@BrBill,
The latest JFrog CLI release includes a **--retries** option for the **jfrog rt upload** command.
Would you like to try it out and let us know if resolves the issue?

**Comment by eyalbe4** [comment]
Awesome @BrBill. Thanks!
