### ISSUE TITLE
windows version cannot download files with special characters in path

### ISSUE THREAD

**Issue by LeiYangGH** [jfrog/jfrog-cli-go#203]
My target files are like:

ncs-temp-local/chengdu_qatest/TTS/Jmeter/testResult/**2018-08-21_06:10:36**/No_1_ThreadNum_10_LoopCount_8.log

$ C:/Install/jfrog.exe rt dl "ncs-temp/chengdu_qatest/TTS/Jmeter/testResult/2018-08-22_08*/*" C:/Users/YANG.LEI/Downloads/arti/
[Info] Searching items to download...
[Info] [Thread 1] Downloading ncs-temp-local/chengdu_qatest/TTS/Jmeter/testResult/2018-08-22_08:02:42/No_2_ThreadNum_200_LoopCount_1.csv
[Info] [Thread 0] Downloading ncs-temp-local/chengdu_qatest/TTS/Jmeter/testResult/2018-08-22_08:02:42/No_1_ThreadNum_100_LoopCount_1.log
[Info] [Thread 2] Downloading ncs-temp-local/chengdu_qatest/TTS/Jmeter/testResult/2018-08-22_08:02:42/No_1_ThreadNum_100_LoopCount_1.csv
[Error] [Thread 1]  Received an error: GetFileAttributesEx C:\Users\YANG.LEI\Downloads\arti\chengdu_qatest\TTS\Jmeter\testResult\2018-08-22_08:02:42\No_2_ThreadNum_200_LoopCount_1.csv: The filename, directory name, or volume label syntax is incorrect.
[Info] [Thread 1] Downloading ncs-temp-local/chengdu_qatest/TTS/Jmeter/testResult/2018-08-22_08:02:42/No_2_ThreadNum_200_LoopCount_1.log
[Error] [Thread 0]  Received an error: GetFileAttributesEx C:\Users\YANG.LEI\Downloads\arti\chengdu_qatest\TTS\Jmeter\testResult\2018-08-22_08:02:42\No_1_ThreadNum_100_LoopCount_1.log: The filename, directory name, or volume label syntax is incorrect.
[Info] [Thread 0] Downloading ncs-temp-local/chengdu_qatest/TTS/Jmeter/testResult/2018-08-22_08:09:24/No_1_ThreadNum_100_LoopCount_1.csv
[Error] [Thread 2]  Received an error: GetFileAttributesEx C:\Users\YANG.LEI\Downloads\arti\chengdu_qatest\TTS\Jmeter\testResult\2018-08-22_08:02:42\No_1_ThreadNum_100_LoopCount_1.csv: The filename, directory name, or volume label syntax is incorrect.
[Error] [Thread 1]  Received an error: GetFileAttributesEx C:\Users\YANG.LEI\Downloads\arti\chengdu_qatest\TTS\Jmeter\testResult\2018-08-22_08:02:42\No_2_ThreadNum_200_LoopCount_1.log: The filename, directory name, or volume label syntax is incorrect.

**Comment by DimaNevelev** [comment]
@LeiYangGH ,
Thank you for reporting this.
What version of Artifactory and JFrog CLI are you using? 
Also, please provide us a debug log level output. You can change the log level to debug by setting the environment variable "JFROG_CLI_LOG_LEVEL=DEBUG".

**Comment by LeiYangGH** [comment]
@DimaNevelev 
$ ./jfrog.exe -version
jfrog version **1.17.1**
for logs, I'll check later since this is night here and the artifactory is in working network.

**Comment by LeiYangGH** [comment]
seems this error happens when the file is transmitted and ready to create local file. windows does not allow  folders with with special characters created.
so is there any walkaround for this? such as renaming(thus removing special characters) the folders before saving to local?

**Comment by DimaNevelev** [comment]
The CLI support wildcards, regular expressions and capture group for such cases.
For your specific case I think this can work:
`jfrog rt dl --flat=true "(ncs-temp/chengdu_qatest/TTS/Jmeter/testResult/2018-08-22_08):(*):(*)/(*)" "C:/Users/YANG.LEI/Downloads/arti/{1}-{2}-{3}/{4}"`
This is the most strict and simple way I could think of. 
In the command above we capture the needed parts of the source pattern using capture group (parenthesis) and then use the captured values in order to build a Windows qualified path. More flexibility can be reached using regular expressions.
I didn't have a chance to test this command on my machine because my version of Artifactory rejects patterns with colons. Let me know if this worked.

**Comment by LeiYangGH** [comment]
@DimaNevelev 
thanks. I tried your sample command, no error reported, however the files are not created as expected, see the attached screen shot:
![jfrog_name_group](https://user-images.githubusercontent.com/5386998/44712453-5e3aa580-aae3-11e8-95be-877da9aa6751.JPG)

**Comment by DimaNevelev** [comment]
Just tested it on a windows machine with the latest versions of Artifactory and the CLI.
Worked as expected.
My Artifactory pattern was: `drive/a/b/a:b:c/a.1.in`. 
Please see what I did:
```
C:\Users\Dima\Downloads>dir arti /s /b
File Not Found

C:\Users\Dima\Downloads>jfrog rt dl --flat=true "(drive/a/b/a):(*):(*)/(*)" "C:/Users/Dima/Downloads/arti/{1}-{2}-{3}/{4}"
[Info] Searching items to download...
[Info] [Thread 2] Downloading drive/a/b/a:b:c/a.1.in
{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}

C:\Users\Dima\Downloads>dir arti /s /b
C:\Users\Dima\Downloads\arti\drive
C:\Users\Dima\Downloads\arti\drive\a
C:\Users\Dima\Downloads\arti\drive\a\b
C:\Users\Dima\Downloads\arti\drive\a\b\a-b-c
C:\Users\Dima\Downloads\arti\drive\a\b\a-b-c\a.1.in
```
Please do the same and provide the exat output of your Windows machine.

**Comment by LeiYangGH** [comment]
@DimaNevelev  thanks for your patience.
I've also found this feature called 'placeholder' in [docs ](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory). I'll have some more experiments.
