### ISSUE TITLE
Support anonymous downloading?

### ISSUE THREAD

**Issue by LeiYangGH** [jfrog/jfrog-cli-go#209]
Hi I'm using 1.19.0, and using in some continuous integration(bamboo plan). 
My artifactory server supports anonymous downloading(for some directories I think, but that's enough, and the administrator did not give us any user name or password, and I didn't see anywhere in the webapp/#/login page to create a personal account).  Downloading by browser manually is OK.

But jfrog cli seems require user name and password.
1. if not configure, then when downloading, jfrog will say
_JFrog CLI with these parameters now will save you having to include them as command options.
You can also configure these parameters later using the 'config' command.
Configure now? (y/n):_ 
and above words will wait user input, which means my CI plan will hang.

2. if I try to configure with empty password, seems it will automatically ignore:
_[root@localhost cp2vm]# ./jfrog rt c golden --url="https://aac-srv-artifactory.mycompany.com/" --user="" --password=""
User:_ 
it will prompt interactively again.

3. if I try to configure with random password:
_[root@localhost cp2vm]# ./jfrog rt c golden \
> --url="https://aac-srv-artifactory.mycompany.com/" \
> --user="x" \
> --password="y"
[Info] Encrypting password...
[Error] Get https://aac-srv-artifactory.nuance.com/api/security/encryptedPassword: EOF_

So what to do to support anonymous downloading?

**Comment by eyalbe4** [comment]
@LeiYangGH,
JFrog CLI uses AQL to find artifacts in Artifactory for most commands.
AQL cannot currently be used without authenticating with Artifactory. That's why anonymous access is currently not allowed in JFrog CLI.

**Comment by LeiYangGH** [comment]
@eyalbe4  I'm not familiar with AQL nor golang. does it mean

**Comment by eyalbe4** [comment]
@asaddamhussain,
How would you suggest JFrog CLI support downloading multiple files (using patterns), without running an AQL search to find the matching files in Artifactory?
