### ISSUE TITLE
Allow downloading the build-info-extractor-maven through Artifactory

### ISSUE THREAD

**Issue by eyalbe4** [jfrog/jfrog-cli-go#211]
When running the *jfrog rt mvn* command for the first time from a buid machine, it attempts to download the build-info-extractor-maven jar from jcenter. We'd like to allow JFrog CLI to fetch this jar through Artifactory, by possibly proxing jcenter.
This could help in cases when the build machine has access to Artifactory only.

**Comment by eddiemcbride** [comment]
Highly interested in this functionality.  Everything is proxied at my company except our Artifactory remote repos so this will help us with implementing the build integration functionality of jfrog-cli into our builds without the dependency issues.

**Comment by eyalbe4** [comment]
@eddiemcbride,
Version 1.22.1 is released and includes this functionality.
See the details [here](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-DownloadingtheExtractorJARs)
We'd appreciate your feedback for the new functionality.
