### ISSUE TITLE
Upload to upload items to repo named 'software'

### ISSUE THREAD

**Issue by madelaney** [jfrog/jfrog-cli-go#217]
With Artifactory (v6.3.3), and the jfrog-cli (v1.19.1) I have a generic repo named `software` (and for testing purposes `sample-repo`).

If I try to upload an file (I tried .tgz,.rar, and .pdf), to my `software` repo, I get the following error:
```
jfrog rt upload Original_SDK.rar /software/Original_SDK.rar
[Info] [Thread 2] Uploading artifact: Original_SDK.rar
[Error] [Thread 2] Artifactory response: 502 Bad Gateway
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Bad Gateway</title>
</head><body>
<h1>Bad Gateway</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
</p>
</body></html>

[Error] [Thread 2] Artifactory response: 502 Bad Gateway
{
  "errors": [
    {
      "status": 403,
      "message": ""
    }
  ]
}
[Debug] [Thread 2]  Artifactory response: 502 Bad Gateway 
[Debug] Uploaded 0 artifacts.
[Error] Failed uploading 1 artifacts.
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
Exit 1
```

However, if I change the repo to `sample-repo`, using the same rar file, the upload is successful:
```
jfrog rt upload Original_SDK.rar /sample-repo/Original_SDK.rar
[Info] [Thread 2] Uploading artifact: Original_SDK.rar
[Debug] [Thread 2]  Artifactory response: 201 Created  (Checksum deploy)
[Debug] Uploaded 1 artifacts.
{
  "status": "success",
  "totals": {
    "success": 1,
    "failure": 0
  }
}
```

To prove this is not a permission issue with the `software` repo. I can use the suggest `curl` command suggested by the Artifactory UI to upload the file without issue.
`curl -H 'X-JFrog-Art-Api:<API_KEY>' -T <PATH_TO_FILE> "https://artifacts.domain.com/softare/<TARGET_FILE_PATH>"`

```
curl -H 'X-JFrog-Art-Api:password12345' -T Original_SDK.rar "https://artifacts.domain.com/softare/Original_SDK.rar"
{
  "repo" : "softare",
  "path" : "/Original_SDK.rar",
  "created" : "2018-09-06T08:02:08.470-04:00",
  "createdBy" : "mdelaney",
  "downloadUri" : "https://artifacts.domain.com/softare/Original_SDK.rar",
  "mimeType" : "application/x-rar-compressed",
  "size" : "631106441",
  "checksums" : {
    "sha1" : "b6c767655db2747f19a4622fcf0505b226ca48ae",
    "md5" : "86db814364cc6bdb96017b68bf6ffeb8",
    "sha256" : "52e913368e386ffecf8eddc00fc82c67a68f34345fce15c4304f403ad5d6e7d8"
  },
  "originalChecksums" : {
    "sha256" : "52e913368e386ffecf8eddc00fc82c67a68f34345fce15c4304f403ad5d6e7d8"
  },
  "uri" : "https://artifacts.domain.com/softare/Original_SDK.rar"
}
```

**Comment by DimaNevelev** [comment]
@madelaney,
In your cURL command, you are using the repo "softare" (missing "w"). In your CLI command, you are using the repo "software". Are you sure the repository "software" exists?
Please try to run the cURL command using the repo "software". If it fails, I suggest you investigate the "request" and "artifactory" logs of your Artifactory instance and your proxy server logs.

**Comment by eyalbe4** [comment]
@madelaney,
Do you need further assistance with this?

**Comment by madelaney** [comment]
@eyalbe4 , nope, it's clear the error was on my side. (Sorry for the delay my reply).
