### ISSUE TITLE
Downloading with dry-run always returns exit code 1

### ISSUE THREAD

**Issue by nedo99** [jfrog/jfrog-cli-go#219]
Hello,

With jfrog CLI version 1.18.0 I started to experience issues when doing downloading files from artifactory with `dry-run` property. If I run the command:` jfrog rt download <remote_folder>/<remote_file> <local_file>`
it works fine. But if I use:  `jfrog rt download --dry-run=true <remote_folder>/<remote_file> <local_file>`
I am getting:
```
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
```

Same applies for `delete` command. Only `upload` works as expected with `dry-run`.
Is this added intentionally and I am misusing dry-run property with jfrog 1.18.0 version.

Looking forward to your reply!

Regards,
Nedim

**Comment by jgeorgeson** [comment]
Failure on dry-run behavior is also present in 1.20.

**Comment by eyalbe4** [comment]
@nedo99 and @jgeorgeson,
Version 1.21.0 resolves this issue.
Please let us know if it works for you.

**Comment by qnerden** [comment]
https://jenkins-infra.caas-ir.autolm.intel.com/blue/organizations/jenkins/GH_AUTOLM-SCRIPTS_DAILY/detail/GH_AUTOLM-SCRIPTS_DAILY/918/pipeline
