### ISSUE TITLE
Log to file instead of stdout

### ISSUE THREAD

**Issue by bts-dido** [jfrog/jfrog-cli-go#241]
I know log level can be set using `JFROG_CLI_LOG_LEVEL` and currently log entries are written to stdout. But instead of using stdout, is there any other way to log into file? I looked through [documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory) but unable to find any useful information. I know I can redirect stdout to file, but I'm just confirming if there any other method.

**Comment by eyalbe4** [comment]
@bts-dido,
The only way to add the log prints into a file is currently redirect the stderr into a file.
Any reason why you'd prefer not to use a redirect?

**Comment by bts-dido** [comment]
@eyalbe4 Thanks for the reply! I was just checking only option is redirect, that's all.

**Comment by eyalbe4** [comment]
Sure @bts-dido.
Let us know if you need more assistance.
