### ISSUE TITLE
Self-signed/issued SAN certificates' verification too strict due to older Golang used

### ISSUE THREAD

**Issue by andreikom** [jfrog/jfrog-cli-go#246]
Using a self-signed/issued certificate with x509 v3 extension with Subject Alternative Name, can result in verification error if used on certain OSs, e.g.: Windows/Linux:

[Error] Get https://artifactorydev.local/artifactory/api/security/encryptedPassword: x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "devartifactory.jfrog.com") 

Above error is originating from JFrog CLI version 1.20.1.

* This did not reproduce on MacOS

A test build with Golang 1.11 resolved this issue.

**Comment by eyalbe4** [comment]
Thanks for filing this @andreikom.
JFrog CLI has been built with go 1.7.1 up until now. 1.11 seems to fix this issue.
The upcoming release will be built with go 1.11 and will therefore include the fix.

**Comment by eyalbe4** [comment]
@andreikom,
Version 1.21.0 has been released and includes this fix.
We'd appreciate your feedback for it.
Thank you.
