### ISSUE TITLE
Panic when --spec-vars ends with semicolon

### ISSUE THREAD

**Issue by bts-dido** [jfrog/jfrog-cli-go#253]
CLI goes into panic when `--spec-vars` option ends with semicolon(`;`). I'm using version `1.20.1`

Command giving the panic is:
`jfrog rt u --spec /path/to/upload/spec.json --spec-vars "foo=bar;"`

Error: 

`panic: runtime error: index out of range`

It seems issue is with this [line](https://github.com/jfrog/jfrog-cli-go/blob/1.20.1/jfrog-cli/utils/cliutils/utils.go#L172) .

**Comment by RobiNino** [comment]
Hi @bts-dido, thanks for pointing this issue out.
We are working on a fix and will release one as soon as possible.

**Comment by RobiNino** [comment]
Hi @bts-dido,
Version 1.21.1 of Jfrog CLI includes the fix for this issue.
We'll appreciate your feedback regarding the fix.

**Comment by bts-dido** [comment]
@RobiNino It works when spec-vars ends with semicolon, but whitespace after semicolon causes panic.

Command giving panic: 
`jfrog-1.21.1 rt u --spec /path/to/upload/spec.json --spec-vars "foo=bar; "`

Error
`panic: runtime error: index out of range`

**Comment by RobiNino** [comment]
Hi @bts-dido, 
Thanks again for pointing it out.
A fix was made and will be included in our next release.

BTW, may I ask if you intentionally end the spec-vars with semicolon / semicolon+space? If so, what is the use case? Thanks.
