### ISSUE TITLE
jfrog cli doesn't build from go source on darwin 64-bit or linux 32-bit

### ISSUE THREAD

**Issue by benharosh** [jfrog/jfrog-cli-go#261]
Can't build the jfrog go cli executable on linux 32-bit or mac (darwin) with go version 1.11:
`$ go get github.com/jfrog/jfrog-cli-go/jfrog-cli/jfrog`
is resulting with the following error:
```
# github.com/jfrog/jfrog-client-go/httpclient
../../go/src/github.com/jfrog/jfrog-client-go/httpclient/client.go:252:10: undefined: archiver.MatchingFormat
../../go/src/github.com/jfrog/jfrog-client-go/httpclient/client.go:306:12: arch.Read undefined (type archiver.Archiver has no field or method Read)
../../go/src/github.com/jfrog/jfrog-client-go/httpclient/client.go:316:20: invalid method expression archiver.Zip.Open (needs pointer receiver: (*archiver.Zip).Open)
../../go/src/github.com/jfrog/jfrog-client-go/httpclient/client.go:476:10: undefined: archiver.MatchingFormat
```
Cheers

**Comment by RobiNino** [comment]
Hi @benharosh,
We just updated the installation instructions on the README, to support our latest release.
Please try building again by following the new instructions.

Would love to hear from you that the installation progress went fine.
Thanks

**Comment by mikemadden42** [comment]
I see something very similar on macOS 10.13.6 and go1.11.2

```bash
$ go get -u -ldflags "-s -w" github.com/jfrog/jfrog-cli-go/jfrog-cli/jfrog 2>&1 | tee jfrog_build_err.log

# github.com/jfrog/jfrog-client-go/httpclient
go/src/github.com/jfrog/jfrog-client-go/httpclient/client.go:252:10: undefined: archiver.MatchingFormat
go/src/github.com/jfrog/jfrog-client-go/httpclient/client.go:306:12: arch.Read undefined (type archiver.Archiver has no field or method Read)
go/src/github.com/jfrog/jfrog-client-go/httpclient/client.go:316:20: invalid method expression archiver.Zip.Open (needs pointer receiver: (*archiver.Zip).Open)
go/src/github.com/jfrog/jfrog-client-go/httpclient/client.go:476:10: undefined: archiver.MatchingFormat
```

**Comment by mikemadden42** [comment]
The following steps do work.  Can you elaborate why building with `go get` no longer works?

```bash
git clone https://github.com/jfrog/jfrog-cli-go/
cd jfrog-cli-go/jfrog-cli/jfrog/
go build -ldflags="-s -w"
```

**Comment by RobiNino** [comment]
Hi @mikemadden42,
Happy to hear the new steps work for you.

Since version 1.21.0 the Jfrog CLI is built using go modules. The project no longer keeps a vendor directory, and jfrog-client-go was separated to a new dependency project. These result in a `go get` failure when working in the legacy GOPATH mode.
Note that `go get` also changed its functionality when working in a module-aware mode.
