### ISSUE TITLE
Unable to download artfiact from remote repository

### ISSUE THREAD

**Issue by asaddamhussain** [jfrog/jfrog-cli-go#276]
Hi,

I am trying to download artifacts from remote repository. Execution completes without downloading anything. But when I execute the command with remote-cache repository, it succeeds with the file downloaded.

Kindly check and help me if it is a bug or an expected behavior.

Thanks!

**Comment by eyalbe4** [comment]
@asaddamhussain,
Supporting this actually depends on [RTFACT-17789](https://www.jfrog.com/jira/browse/RTFACT-17789).

**Comment by asaddamhussain** [comment]
But when I give virtual repo also, it is not downloading the cached artifacts?
My artifactory server version is 4.4.3 rev 40110

**Comment by asaddamhussain** [comment]
@eyalbe4 
Any help you can do here?

Thanks!

**Comment by eyalbe4** [comment]
@asaddamhussain,
AQL searcher are currently supported only for local repositories. You can run an AQL search on a virtual repository, but it'll only find items that are stored on a local repository which the virtual includes.
The above Jira issue intends to fix this issue.

**Comment by eyalbe4** [comment]
@asaddamhussain,
Since adding support for this is already tracked by [RTFACT-17789](https://www.jfrog.com/jira/browse/RTFACT-17789) and will probably require no changes in the source code of JFrog CLI, I'm closing this issue.
