### ISSUE TITLE
Artifactory download hangs incase of network blip

### ISSUE THREAD

**Issue by bts-dido** [jfrog/jfrog-cli-go#288]
Maybe duplicate of #177 but I'm seeing issue on newer version - `1.20.0`
Here is the stacktrace when CLI is hanging. It seems issue is with `io.Copy`, it waits for EOF, but server not sending EOF because of network blip. Setting timeout in http client will solve this, but currently it's 0.  

`goroutine 705 [IO wait, 41 minutes]:
net.runtime_pollWait(0x7fc15845f048, 0x72, 0x35)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4200ddaa0, 0x72, 0xc4201e1590, 0xc4200100a8)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4200ddaa0, 0xf2a760, 0xc4200100a8)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4200dda40, 0xc4203d8dba, 0x3246, 0x3246, 0x0, 0xf2a760, 0xc4200100a8)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42002c138, 0xc4203d8dba, 0x3246, 0x3246, 0x0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420227a40, 0x7fc15845f1c8, 0xc42002c138, 0x101d, 0xc42002c138, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc4206c1500, 0xbf8b17, 0xc4206c1600, 0x1)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/crypto/tls/conn.go:619 +0x1fa
crypto/tls.(*Conn).Read(0xc4206c1500, 0xc4206de000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/crypto/tls/conn.go:1109 +0x116
net/http.(*persistConn).Read(0xc420199200, 0xc4206de000, 0x8000, 0x8000, 0xc4206de000, 0x1000, 0x1000)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).Read(0xc4201d9560, 0xc4206de000, 0x8000, 0x8000, 0xc4206de000, 0x1000, 0x40d8c8)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/bufio/bufio.go:199 +0xc7
io.(*LimitedReader).Read(0xc4203f4180, 0xc4206de000, 0x8000, 0x8000, 0x451290, 0xc4201e1a88, 0xc4201e1a90)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/io/io.go:436 +0x6c
net/http.(*body).readLocked(0xc42022e100, 0xc4206de000, 0x8000, 0x8000, 0x0, 0x0, 0xc4201e1b30)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/net/http/transfer.go:651 +0x61
net/http.(*body).Read(0xc42022e100, 0xc4206de000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/net/http/transfer.go:643 +0xf6
net/http.(*bodyEOFSignal).Read(0xc42022e140, 0xc4206de000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/net/http/transport.go:1974 +0x116
io.copyBuffer(0xf28fa0, 0xc4201ac298, 0xf28ba0, 0xc42022e140, 0xc4206de000, 0x8000, 0x8000, 0xae07a0, 0x0, 0xf28ba0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/io/io.go:390 +0x147
io.Copy(0xf28fa0, 0xc4201ac298, 0xf28ba0, 0xc42022e140, 0xc42022e140, 0xc4203f41c0, 0x16)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.7.1/src/io/io.go:360 +0x68
github.com/jfrog/jfrog-cli-go/jfrog-client/httpclient.(*HttpClient).downloadFileRange(0xc42002c2b0, 0xc4203a6ed0, 0x2e, 0xc420154140, 0x91, 0xc4203a6ed0, 0x2e, 0xc420417fa0, 0x1e, 0xc4203a6f00, ...)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrog/jfrog-cli-go/jfrog-client/httpclient/client.go:524 +0x665
github.com/jfrog/jfrog-cli-go/jfrog-client/httpclient.(*HttpClient).downloadChunksConcurrently.func1(0xc42037f5f0, 0x3, 0x3, 0xc42037f620, 0x3, 0x3, 0xc42002c2b0, 0xc4203a6ed0, 0x2e, 0xc420154140, ...)
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrog/jfrog-cli-go/jfrog-client/httpclient/client.go:407 +0xe5
created by github.com/jfrog/jfrog-cli-go/jfrog-client/httpclient.(*HttpClient).downloadChunksConcurrently
	/var/lib/jenkins/workspace/EcoSystem/jfrog-cli-release/temp/src/github.com/jfrog/jfrog-cli-go/jfrog-client/httpclient/client.go:412 +0x2f7`

**Comment by bts-dido** [comment]
It seems Artifactory server sends unexpected TCP RST packet (connection reset by peer) and causing hang. I'm able to simulate it in my test env.

**Comment by eyalbe4** [comment]
@bts-dido, https://github.com/jfrog/jfrog-client-go/pull/29 by @barbelity should fix this issue.
It is expected to be released as part of the upcoming patch within a few days.

**Comment by bts-dido** [comment]
@eyalbe4 Thanks! Let me know when fix is released.

**Comment by barbelity** [comment]
@bts-dido, JFrog CLI version 1.23.2 should solve this issue.
You can check out [the relevant commit](https://github.com/jfrog/jfrog-client-go/commit/43a1198952493b7cb076a3476f98ead7c188cff3#diff-018ca4d91b783eaec414d24ff7533348R37) in jfrog-client-go.
Please let us know if it solved this issue for you.

**Comment by bts-dido** [comment]
@barbelity Thanks! I see issue is resolved. I'm able to confirm it on my local env. 

I see you guys also fixed attempts are not working issue also.
