### ISSUE TITLE
1.23.0 jfrog rt download --flat now requires [target pattern] to be set

### ISSUE THREAD

**Issue by djgilcrease** [jfrog/jfrog-cli-go#298]
`jfrog rt download --threads 1 --flat=true --url "${ART_URL}" --apikey "${ART_DEV_TOKEN}" --sort-by created --sort-order desc --limit 1 --explode --props "product.name=${PRODUCT_NAME};product.number=${PRODUCT_SEMVER}" "${ART_
DEV_REPO}/projectA/*"`

```
[Info] Searching items to download...
[Info] [Thread 0] Downloading dev/projectA/0.2.0/projectA-0.2.0-m.prerelease.1856457.tgz
[Info] [Thread 0] Extracting archive: projectA-0.2.0-m.prerelease.1856457.tgz to 
[Error] [Thread 0]  Received an error: projectA/: illegal file path
[Error] projectA/: illegal file path
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
```

notice the missing path after the `Extracting archive` line

this used to work in 1.14.0

**Comment by djgilcrease** [comment]
also a note, [target pattern]  must be an absolute path now

**Comment by barbelity** [comment]
Thank you @djgilcrease for reporting this issue.
It seems to occur when using the 'explode' flag without providing a 'target' argument. 
We will let you know once this is fixed.

**Comment by eyalbe4** [comment]
@djgilcrease - the latest JFrog CLI release includes a fix for this issue.
We'd appreciate your feedback for it.

**Comment by djgilcrease** [comment]
this works as expected now, thank you.
