### ISSUE TITLE
Support Relative Directories

### ISSUE THREAD

**Issue by bloudraak** [jfrog/jfrog-cli-go#314]
Consider the following snippet we often use on Linux 

```
mkdir -p ./tools/MyApp/
cp -R ./MyApp/1.2.3/ ./tools/MyApp/
```

It will copy the contents of `./MyApp/1.2.3/`, such as `./MyApp/1.2.3/bin/myapp` to `./tools/MyApp/`, such as `./tools/MyApp/bin/myapp`.

Consider the `jfrog-cli` equivalent:

```
jfrog rt dl --url "artifactory.example.com" --apikey "<key>" --retries=10 --threads=10 --recursive=true --flat=false "my-repo/MyApp/1.2.3/" "./tools/MyApp"
```

It will copy `my-repo/MyApp/1.2.3/bin/myapp` to `./tools/MyApp//MyApp/1.2.3/bin/myapp` which makes it difficult to use. 

Can you add another flag, e.g. `--relative`, so that it works similar to `cp` such that `my-repo/MyApp/1.2.3/bin/myapp` is copied to `./tools/MyApp/bin/myapp`? 

It is worth considering that the storage in Artifactory may be more involved than what we need locally. We may store applications in versioned folders (e.g. `1.2.3` above); and often the folder structure in Artifactory is undesired locally; especially when all I need is the contents of `my-repo/MyApp/1.2.3/` without any mention of that structure locally.  If the cli can do this, then it would greatly simplify downstream scripts which now requires to be aware of the Artifactory structure.

**Comment by eyalbe4** [comment]
@bloudraak,
You can achieve what you're looking for using [Placeholders](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingPlaceholders). Placeholders allow to construct your destination path dynamically, based on the source path in Artifactory.
Please let us know if this helps and if you have follow up questions.
