### ISSUE TITLE
Multi-Module builds

### ISSUE THREAD

**Issue by NasAmin** [jfrog/jfrog-cli-go#317]
Hi,

We are build multiple nuget based solution. We have multiple solutions in the root project. Currently I am having to publish each sub solution as a separate build.

Is it possible to treat the multiple solutions as modules and publish and promote their artifacts under a single build.

Example:
Currently:
Root folder --->
   Solution 1 ---> Currently a separate build info
   Solution 2 --> Currently a separate build info

What I am after
Root Folder --> Build info
   Solution 1 --> Treat this as a module and show it under the Module view in Artifactory Build info tab
   Solution 2 --> Treat this as a module and show it under the Modules view in Artifactor Build info tab

Is the above possible?

Regards,

Nas

**Comment by eyalbe4** [comment]
@NasAmin,
You can include multiple solutions in one build-info.
You can do this by building each solution with the same ```--build-name``` and ```--build-number``` without running ```jfrog rt build-publish``` after every build.
Once all fo the solutions are built, you then run one ```jfrog rt build-publish``` with the same build name and build number you used for all the builds. This will publish one build-info, which includes each solution previously built as a module.
Please let me know if this is what you're looking for.

**Comment by eyalbe4** [comment]
@NasAmin,
I'm closing this issue for now.
Please let us know if you need further assistance.
