### ISSUE TITLE
Changing default JFROG_CLI_TEMP_DIR is ignored

### ISSUE THREAD

**Issue by Amos-85** [jfrog/jfrog-cli-go#318]
I'm trying to change the tmp directory of jfrog cli in version 1.23.1
after exporting JFROG_CLI_TEMP_DIR environment variable the jfrog cli app still use the default  /tmp folder

**Comment by thllxb** [comment]
@Amos-85 
Before they fix the [jfrog-client-go](https://github.com/jfrog/jfrog-client-go) which is the lib for [jfrog-cli-go](https://github.com/jfrog/jfrog-cli-go), you can set the environment variable **TMPDIR** to the path you want, and it would be picked up by Go-lang as the default tmp path, assuming you can run your jfrog cli in an environment where changing the default tmp path won't affect others.

**Comment by barbelity** [comment]
@Amos-85, @thllxb 
Our latest release of JFrog CLI, version 1.25.0, fixes this issue.
You can also see the relevant commit [here](https://github.com/jfrog/jfrog-cli-go/commit/e4238e75f1cd18de7dddb8c60b514152afe6b9f5#diff-615f4de5ec6c219ff02cdedad8497cc8R32).
Your feedback for it is highly appreciated.

**Comment by Amos-85** [comment]
@barbelity 
thanks for confirmation.

**Comment by thllxb** [comment]
@barbelity Thank you for the fix. The new version works as expected.

**Comment by barbelity** [comment]
@Amos-85 @thllxb Thanks for the update. I'm closing the issue.
