### ISSUE TITLE
Bug: jfrog rt build-add-git must strip credentials from vcsUrl

### ISSUE THREAD

**Issue by mfriedenhagen** [jfrog/jfrog-cli-go#326]
* We use GitLab for building software.
* GitLab creates a temporay check-out token for every build job. The username is always `gitlab-ci-token`.
* When invoking `jfrog rt build-add-git` the complete URL is stored in Artifactory.
* This leads to leakage of (albeit) temporary read-only credentials.
```
    "vcsRevision": "0bd112128dc5750affe9266396207a0548b12848",
    "vcsUrl": "https://gitlab-ci-token:34XXXXXXXXXXXXXXaVaG@gitlab.example.com/gitlab-group/gitlab-project.git",
```

**Comment by barbelity** [comment]
@mfriedenhagen,
JFrog CLI version 1.24.0 is released, and contains a fix for this issue.
You can view the relevant commit [here](https://github.com/jfrog/jfrog-cli-go/commit/704c033266d82c80ac4a33f2e53bebf8569d2e2a#diff-6d53d38e202a17ffc1da970a4f6359a5R78).
We'd appreciate your feedback for it.

**Comment by eyalbe4** [comment]
@mfriedenhagen,
I'm closing this issue for now. Please let us know if you have any questions.

**Comment by mfriedenhagen** [comment]
Sorry, thank you. Works now.
