### ISSUE TITLE
Compile binaries with CGO_ENABLED=0

### ISSUE THREAD

**Issue by JordanSussman** [jfrog/jfrog-cli-go#328]
Hello,

Any chance you are open to modifying the [Jenkinsfile](https://github.com/jfrog/jfrog-cli-go/blob/master/Jenkinsfile#L94) to build with `CGO_ENABLED=0` instead of the default of `CGO_ENABLED=1`? I have some use cases where I want to utilize the binary on systems where `CGO_ENABLED=1` doesn't function. 

Looks like the [Dockerfile](https://github.com/jfrog/jfrog-cli-go/blob/master/Dockerfile#L5) is already utilizing `CGO_ENABLED=0` but the published binaries are not. My current workaround is to the build from source but I would prefer not to do so.

Thanks

**Comment by eyalbe4** [comment]
@JordanSussman,
Thanks for sharing this requirement.
We released JFrog CLI 1.24.3, which was built using the newly added [build.sh](https://github.com/jfrog/jfrog-cli-go/blob/master/build.sh).
We'd appreciate your feedback for it.

**Comment by JordanSussman** [comment]
Hey @eyalbe4,

I just validated that 1.24.3 works for my needs.

Thanks!
