### ISSUE TITLE
RegExp Syntax - Not following golang syntax

### ISSUE THREAD

**Issue by cpyfferoen** [jfrog/jfrog-cli-go#332]
attempting to use the `--exclude-patterns` flag on upload and the syntax seems to be somewhat randomly made up because a technically invalid syntax is working, and the correct syntax is not working 

correct syntax would be: `(?i).*install.*pack.*`
this is what i'm forced to have: `(?i)*install*pack*` - this is not a valid regular expression - and would behave completely not as expected from anyone who knows what they are doing with regular expressions.

I'm trying to filter:
- InstallationPackage
- installpack
- installationpackage

Fine, you needed your own syntax or couldn't parse `.` or some other random reasoning.. But please write it down somewhere.. With big red flags "YOU CAN'T USE GOLANG SYNTAX - WE MADE UP OUR OWN"

my command `jfrog rt u --dry-run=true --flat=false --regexp=false --exclude-patterns="(?i)*emulate.ACD;Ladder/**/;*.dwg;*.vb;*Code*;*_sgvault*;(?i)*install*pack*" "(*).(*)" "generic-local/sites/501XX/50100_LOL_SIOUX_FALLS/ONSITE/{1}"`

Also - this isn't working w/ `--regexp=true` --> `[Error] error parsing regexp: missing argument to repetition operator: '*'`
I have no idea why that is either. So far the "documentation" has been a bit lacking/confusing in my opinion.

**Comment by eyalbe4** [comment]
@cpyfferoen,
The difference between the two exclude patterns that you shared, is that the first one is a wildcards pattern and the second one is a regular expression. The upload command is the only command that can be used with regular expressions (when adding the *--regexp* option). The default is wildcards patterns.
If I understand you correctly, you are basoc saying that the *--regexp* option is ignored for the value of *--exclude-patterns*. 
Let us chance that and we'll update shortly.

**Comment by eyalbe4** [comment]
@cpyfferoen,
Adding to my previous comment - 

It appears that the following error:
```Error] error parsing regexp: missing argument to repetition operator: '*'```
is thrown from the following coder line:
```patternRegex, err := regexp.Compile(uploadParams.GetPattern())```
when this happens ```uploadParams.GetPattern()``` gets ```(*).(*)``` in your case.
In other wards, if you run the following go code:
```regexp.Compile("(*).(*)")``` - you will receive the same error. The code doesn't do anything else other than the above. It looks like go cannot accept this input/

In addition, the ```--exclude-patterns``` option behaves as expected - it uses wildcards by default and a regular expression if ```--regexp``` is set to true.
We did step on one issue though - the ```--exclude-patterns``` option is used by other commands, which do not support the ```--regexp option```. The help topic for the ```--exclude-patterns``` in those commands says that ```--regexp``` is supported.
We pushed https://github.com/jfrog/jfrog-cli-go/commit/79a3bd4ce292df8b0526d46ed11999e441a94ff0 to fix this. We'll soon update the online documentation as well.

Please let me know what you think. Thanks!

**Comment by cpyfferoen** [comment]
I understand - with the info you provided i can hopefully figure out what i need to pass in so GO can evaluate the Regular Expression and pick up all the of Folders/Files in the current directory. 

It is really a separate issue so I think this one can probably be closed. 

Would be nice if the wiki had a little bit broader set of examples for these particular flags/cases I'm exercising, but can't please everyone :)

Thanks @eyalbe4

**Comment by eyalbe4** [comment]
Thanks you @cpyfferoen Your feedback is really appreciated!
We've added Example 3 and Example 4 to the [upload command documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UploadingFiles).
I'm closing this issue. Please let us know if you need additional assistance.
