### ISSUE TITLE
request:  Allow setting values ​​of properties for the promotion of build

### ISSUE THREAD

**Issue by maras1** [jfrog/jfrog-cli-go#349]
Currently, the build promotion command does not allow setting properties for artefacts contained in the build. 
This should be done in a similar way to Build Promotion rest endpoint.
Business case / use case:
The introduction of this new functionality will enable the introduction of artifact retention based on property values ​​for artifacts.

As part of the process of installing artifacts on the test or production environment, the build will be promoted to the appropriate repository. For artifacts, the property specifying the date of installation and flags indicating which environment artifacts have been installed will be added. Based on these properties, an effective retention policy for artifacts based on metadata assigned to artifacts can be entered for each repository.

**Comment by maras1** [comment]
We want to use this functionality especially during the promotion of builds containing docker images.
Currently, it is not possible to enter property values ​​when the docker-push CLI command is performed

**Comment by eyalbe4** [comment]
@maras1 - thanks for sharing this requirement.
@AlexeiVainshtein  added this functionality in https://github.com/jfrog/jfrog-cli-go/commit/a57cc59184e976d7dc0889d3610a0feffaaec54d (thanks @AlexeiVainshtein!)
It's been released as part of version 1.25.0.
We'd appreciate your feedback for it.
