### ISSUE TITLE
Gradle build (using proxy in the middle) not making use of proxy for publish

### ISSUE THREAD

**Issue by shahiinn** [jfrog/jfrog-cli-go#350]
We have noticed that for a gradle build with a proxy server (set using HTTP_PROXY) using JFrog cli, all the dependencies will be fetched through the proxy instance however when it comes to uploading of artifacts it's not making use of the proxy instance.

you can reproduce the issue by doing the following steps:
1. Configure a proxy for JFrog cli using the following command
       `export  HTTP_PROXY=<proxy-ip>:<port>`
2. Configure Artifactory with JFrog cli
       `jfrog rt c`
3. Run the build against a gradle project (example : https://github.com/jfrog/project-examples/tree/master/gradle-examples/gradle-example)
      `jfrog rt gradle "clean artifactoryPublish --debug -b build.gradle" config --build-name=gradle-build-test --build-number=1`

**Comment by eyalbe4** [comment]
@shahiinn,
The above commits by @AlexeiVainshtein are released as part of version 1.25.0 (thank you @AlexeiVainshtein).
We'd appreciate you feedback for it.
