### ISSUE TITLE
JFrog CLI does not work with docker CE 17.05

### ISSUE THREAD

**Issue by scottrus** [jfrog/jfrog-cli-go#354]
Since 1.20.x of JFrog CLI, support for older docker login without --password-stdin is broken. The PR #353 would be a good workaround if it gets released.

**Comment by maras1** [comment]
The fix of this error is very important to us. We use Openshift, and there the client docker version is very old. No fix makes it difficult to implement CI / CD automation for Docker images based on Jfrog CLI

**Comment by eyalbe4** [comment]
@scottrus and @maras1,
Thanks for sharing this.
I guess we can add a ```--skip-login``` option to the ```jfrog rt docker-push``` command.
Would that resolve the issue for you?

**Comment by scottrus** [comment]
Yes, that would work for our use case of current jfrog + older docker without the --passwd-stdin option.

**Comment by djgilcrease** [comment]
This would work for my usecase as well and would invalidate the need for #353

**Comment by eyalbe4** [comment]
Great - I created https://github.com/jfrog/jfrog-cli-go/pull/380.
I guess this issue can be closed then @scottrus.

**Comment by eyalbe4** [comment]
@djgilcrease, @scottrus and @maras1,
https://github.com/jfrog/jfrog-cli-go/pull/380 made it into the latest release.
Looking forward to your feedback.
Closing this issue.
