### ISSUE TITLE
jfrog rt build-promote fails when multiple builds with same name and number have been uploaded

### ISSUE THREAD

**Issue by daveneeley** [jfrog/jfrog-cli-go#362]
Artifactory returns 400 Bad Response to jfrog-cli if two builds have been uploaded with the same name and number.

```
jfrog rt bpr my_build_name 1.2.3 target-repo
[Info] Promoting build...
[Error] Artifactory response: 400 Bad Request
{
  "errors": [
    {
      "status": 400,
      "message": "Unable to find artifacts of build 'my_build_name' #1.2.3: aborting promotion."
    }
  ]
}
```
Multiple builds of the same name and number can get into Artifactory via steps described in https://github.com/jfrog/teamcity-artifactory-plugin/issues/35

The Artifactory rest API only returns the most recent buildinfo object, not both, which means it cannot be used as a workaround.

**Comment by djgilcrease** [comment]
I find this very annoying as well. the build should either be unique on name/number or when you publish to an existing name/number it should add/replace artifacts

**Comment by eyalbe4** [comment]
Thanks for reporting this issue @daveneeley and @djgilcrease.
We opened [RTFACT-19143](https://www.jfrog.com/jira/browse/RTFACT-19143) on Artifactory's JIRA project to track this request.

**Comment by daveneeley** [comment]
If jfrog-cli creates the duplicate buildinfos, as outlined in the linked gist, then there is no failure but only the most recent buildinfo will be promoted.

https://gist.github.com/daveneeley/18a72abe2e9a4c5de9d256b1115d5cdb

**Comment by eyalbe4** [comment]
@daveneeley and @djgilcrease,
Thanks for sharing your input and the information.
Since we now have the above JIRA issue open, and if a behavior change will be made, it'll probably be on the REST endpoint (and not in JFrog CLI), I'm closing this issue for now.
Feel free to add more comments here.
