### ISSUE TITLE
Include folders when deleting based on match

### ISSUE THREAD

**Issue by efaverman** [jfrog/jfrog-cli-go#363]
When deleting based on pattern, folders are excluded from delete, resulting in empty folders.

E.g.: running `jfrog rt delete --spec spec.json` and spec.json contains below, I am left with empty folder `team-docker-dev-local/myapp-docker/admin-server/1.1.3/` 

`{
    "files": [
            {
                "aql": {
                    "archive.entries.find": {
                        "created" : {"$before" : "2mo"},
                        "repo" : "team-docker-dev-local",
                        "path": {"$match":"*myapp-docker/admin-*/1.*"},
                        "path": {"$nmatch":"*myapp-docker/admin-*/1.5.9*"},
                    }
                }
            }
    ]
}`

**Expected behavior:**
Since `team-docker-dev-local/myapp-docker/admin-server/1.1.3/` matches `{"$match":"*myapp-docker/admin-*/1.*"},` I expect **folder** to be deleted, not just contents of folder

**Comment by eyalbe4** [comment]
@efaverman,
The spec you provided seems to be invalid - 
```
jfrog rt s --spec=spec 
[Error] invalid character '}' looking for beginning of object key string
```
It also looks like you're searching for archive entries and not items - ```archive.entries.find```.
Folders however are items.
Let me know what you think.

**Comment by eyalbe4** [comment]
@efaverman,
Please let us know if you need additional help with this.
I'm closing this issue for now.
