### ISSUE TITLE
Error when specifying url and authentication details

### ISSUE THREAD

**Issue by Cushdrive** [jfrog/jfrog-cli-go#377]
I'm receiving the following error whenever the --url, --username or --password flags are provided to the jfrog command:

[Error] flag provided but not defined -url

Example command:
jfrog rt mvnc ~/Downloads/jfrog_build_def --url=http://localhost:8081/artifactory/ --user=xxxxxx --password=xxxxxx

> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F2104

> go version
go version go1.12.5 darwin/amd64

> jfrog -version
jfrog version 1.25.0

I can also reproduce this using the docker image.

**Comment by AlexeiVainshtein** [comment]
Hi @Cushdrive 

Thank you for opening this issue. The mvnc command doesn't receive any flags. This is an interactive command to create the config yaml file for the mvn command to run, therefore, no flags can be passed to this command. You can see the usage of each command by running `jfrog rt <command name>`. This will print the help information with the flags that can be passed to this command.
