### ISSUE TITLE
Publishing a nested node package

### ISSUE THREAD

**Issue by bstaley** [jfrog/jfrog-cli-go#378]
Our application has the following structure after being built:
```
/dist
|    |__/lib
|          |__package.json
|
/misc folders
|
misc files
|
package.json 
```

We need to publish the package under the dist/lib folder not the one at the root. I don't see any way in the documentation to point to a specific package.json when using npm-publish. later we might decide to add more libs, ex. (dist/lib1, dist/lib2). how can we handle this?

**Comment by eyalbe4** [comment]
@bstaley,
When running the *npm-publish* command from within the *dist/lib* folder, does the publish work properly?
If so, do you see an issue with this solution?

**Comment by eyalbe4** [comment]
@bstaley,
I'm closing this issue for now, but please let me know if you'd like to continue discussing this.

**Comment by bstaley** [comment]
@eyalbe4,
I was finally able to test this out and it worked. We just `cd ./dist/lib` right before calling `npm-publish` and presto we get the results we expect. Thanks for the suggestion!
