### ISSUE TITLE
File upload fails with "wrong number of arguments"

### ISSUE THREAD

**Issue by antonarhipov** [jfrog/jfrog-cli-go#395]
```
$ jfrog --version
jfrog version 1.25.0
```

The official [documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory) says the command to upload a file is as follows:
```
$ jfrog rt command-name global-options command-options arguments
```

Executing the command:

```
$ jfrog rt u --url=http://localhost:8040/artifactory/ --user=xxxxx --password=yyyyy file.txt generic-local/myfile/1/ --build-number=1 --build-name=myfile
```
Results in:
```
[Error] Wrong number of arguments. You can read the documentation at https://www.jfrog.com/confluence/display/CLI/JFrog+CLI
```

After surfing the internets for a solution I noticed that some of the examples list the global options last. So this works:
```
jfrog rt u file.txt generic-local/myfile/2/ --build-number=2 --build-name=myfile --url=http://artifactory/ --user=xxxxx --password=yyyyy
```
So is the documentation outdated or is it a bug in the tool?

**Comment by eyalbe4** [comment]
@antonarhipov,
Notice that you initially mixed arguments with command options - 
You command structure was:
1. The command name - **jfrog rt u**
2. Global command options - **--url=http://localhost:8040/artifactory/ --user=xxxxx --password=yyyyy**
3. Command arguments - **file.txt generic-local/myfile/1/**
4. Command options - **--build-number=1 --build-name=myfile**

You can either specify all the options and then all the arguments or vice versa.
I think that the documentation supports this convention.

**Comment by antonarhipov** [comment]
@eyalbe4 so it's either
```
jfrog rt u --url --user --password --build-number --build-name source traget
```

or

```
jfrog rt u source traget --url --user --password --build-number --build-name 
```
?

So I'm correct that the doc is not in line with the implementation?

**Comment by blackknight36** [comment]
@eyalbe4 It appears that this is still a problem.  Even with *no* arguments provided the jf command fails with an error stating.

```08:51:31 [🚨Error] Wrong number of arguments (4).```

The command I used is as follows.

```
jf rt upload ~/Downloads/nomachine-workstation_*.deb cpe-generic/nomachine/
```

I am running jf version 2.22.0 on MacOS 10.6.2.
