### ISSUE TITLE
jfrog rt set-props does not work (deletes properties instead)

### ISSUE THREAD

**Issue by tdmx** [jfrog/jfrog-cli-go#397]
Unable to set properties of artifacts using `jfrog rt set-props`. This command deletes properties instead. Observed in jfrog version 1.26.0.
Digging into the source code, I found this:
https://github.com/jfrog/jfrog-cli-go/blob/1fe8f138afca70cbcf8459c71c3554ae00c98d25/artifactory/commands/generic/setprops.go#L37

Shouldn't this be calling [`serviceManager.SetProps`](https://github.com/jfrog/jfrog-client-go/blob/98eceff47197d9d716b2a5ce41991af46d6ac5e3/artifactory/services/props.go#L42)?

**Comment by AlexeiVainshtein** [comment]
Hi @tdmx 

Thank you for reporting this. We will work on this issue and let you know when the new version will be released.

**Comment by eyalbe4** [comment]
@tdmx,
The issue is fixed as part of version 1.26.1.
Thanks

**Comment by tdmx** [comment]
Thank you for the quick response. All working as expected now!
